name: 'Create package'

on:
  workflow_dispatch:
    inputs:
      pe-version:
        description: 'Puppet Enterprise version to create package for'
        required: true
        type: string
      platform:
        type: choice
        description: Which platform to build for
        options: 
          - el-7
          - el-8

jobs:
  create-package:
    runs-on: ubuntu-latest
    name: Build ${{ inputs.platform }} package
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build package for ${{ inputs.pe-version }}
        uses: ./.github/actions/create-package-for-${{ inputs.platform }}
        id: build-package
        with:
          pe-version: ${{ inputs.pe-version }}
      - name: Upload ${{ inputs.pe-version }} package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build-package.outputs.filename }}
          path: ${{ steps.build-package.outputs.filename }}
          retention-days: 1
