name: 'Create packages'

on:
  workflow_dispatch:
    inputs:
      pe-version:
        description: 'Puppet Enterprise version to create RPM for'
        required: true
        type: string

jobs:
  create-el-8-rpm:
    runs-on: ubuntu-latest
    name: 'Build package for EL 8'
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Build package'
        uses: ./.github/actions/create-package-for-el-8
        id: 'el-8-rpm'
        with:
          pe-version: ${{ inputs.pe-version }}
      - name: 'Upload package'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.el-8-rpm.outputs.filename }}
          path: ${{ steps.el-8-rpm.outputs.filename }}
          retention-days: 1
  create-el-7-rpm:
    runs-on: ubuntu-latest
    name: 'Build package for EL 7'
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Build package'
        uses: ./.github/actions/create-package-for-el-7
        id: 'el-7-rpm'
        with:
          pe-version: ${{ inputs.pe-version }}
      - name: 'Upload package'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.el-7-rpm.outputs.filename }}
          path: ${{ steps.el-7-rpm.outputs.filename }}
          retention-days: 1
